"""
I.R.I.S. — Dreaming Agent (π₂ Mockup)
========================================
The π₂ Anticipatory Mode agent. Runs simultaneously with the execution agent,
fed from the same digital twin state. Continuously cycles through pre-computed
scenarios, scores them using the weighted objective function, and holds the
best solution in reserve for deployment.

This agent NEVER interrupts the execution agent — it runs on every clock tick
in parallel. This is the key demonstration property of dual cognitive mode.

π₂ responsibilities:
  - Maintain a library of dreamed scenarios covering worst-case events
  - Score each scenario using: score = w1*reward_intensity + w2*safety_margin
  - Weights are DYNAMIC — shift based on proximity variable state
  - Detect when a dreamed scenario is materialising in real sensor data
  - Hold best solution in reserve until triple-lock gate fires
  - Emit micro-reward on each viable dream (adds to f(π₂))
  - Emit macro-reward on successful deployment (adds large spike to f(π₂))

Multi-agent PPO fleet sharing is modelled via a shared scenario library
that all agents in a fleet would contribute to and draw from.
"""

import numpy as np
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


# =============================================================================
# SCENARIO LIBRARY
# Pre-computed worst-case scenarios dreamed by π₂.
# In production these would be generated by the quantum dreaming process.
# Each scenario has a navigation handover solution and scoring parameters.
# =============================================================================

@dataclass
class DreamedScenario:
    id:              int
    name:            str
    trigger_rule:    str          # which π₁ rule triggers this scenario
    trigger_signal:  str          # which proximity variable to match
    trigger_thresh:  float        # proximity score threshold for match
    solution_name:   str          # pre-computed response
    reward_score:    float        # reward intensity if deployed (0-1)
    safety_score:    float        # safety margin of solution (0-1)
    weighted_score:  float = 0.0  # computed dynamically
    confidence:      float = 0.0  # current match confidence (0-1)
    viable:          bool  = False


SCENARIO_LIBRARY: List[DreamedScenario] = [

    # ── GNSS / Communication scenarios ───────────────────────────────────────
    DreamedScenario(
        id=1, name="GNSS Total Loss — IRS Fallback",
        trigger_rule='communication', trigger_signal='gnss_signal',
        trigger_thresh=0.55,
        solution_name="IRS Dead Reckoning + Celestial Backup",
        reward_score=0.61, safety_score=0.95,
    ),
    DreamedScenario(
        id=2, name="GNSS Partial Degradation — VOR Hybrid",
        trigger_rule='communication', trigger_signal='gnss_signal',
        trigger_thresh=0.35,
        solution_name="VOR/DME + IRS Hybrid Navigation",
        reward_score=0.81, safety_score=0.93,
    ),
    DreamedScenario(
        id=3, name="GNSS Spoofing — Terrain Reference",
        trigger_rule='communication', trigger_signal='gnss_signal',
        trigger_thresh=0.45,
        solution_name="Terrain Referenced Navigation (TRN)",
        reward_score=0.79, safety_score=0.88,
    ),
    DreamedScenario(
        id=4, name="GNSS Jamming — Optical Flow Fusion",
        trigger_rule='communication', trigger_signal='gnss_signal',
        trigger_thresh=0.50,
        solution_name="Optical Flow + IRS Sensor Fusion",
        reward_score=0.83, safety_score=0.86,
    ),
    DreamedScenario(
        id=5, name="GNSS Loss Oceanic — Celestial Nav",
        trigger_rule='communication', trigger_signal='gnss_signal',
        trigger_thresh=0.60,
        solution_name="Star Tracker Celestial Navigation",
        reward_score=0.55, safety_score=0.97,
    ),

    # ── Speed envelope scenarios ──────────────────────────────────────────────
    DreamedScenario(
        id=6, name="Overspeed Warning — Throttle Reduction",
        trigger_rule='speed_envelope', trigger_signal='mach',
        trigger_thresh=0.50,
        solution_name="Throttle Back + Spoiler Deploy",
        reward_score=0.88, safety_score=0.94,
    ),
    DreamedScenario(
        id=7, name="Mach Tuck — Nose Up Recovery",
        trigger_rule='speed_envelope', trigger_signal='mach',
        trigger_thresh=0.75,
        solution_name="Elevator Nose-Up + Drag Device",
        reward_score=0.72, safety_score=0.91,
    ),

    # ── Stall scenarios ───────────────────────────────────────────────────────
    DreamedScenario(
        id=8, name="High AoA — Stall Recovery",
        trigger_rule='stall_margin', trigger_signal='alpha_deg',
        trigger_thresh=0.55,
        solution_name="Nose Down + Full Throttle Recovery",
        reward_score=0.85, safety_score=0.92,
    ),

    # ── Fuel scenarios ────────────────────────────────────────────────────────
    DreamedScenario(
        id=9, name="Low Fuel — Divert to Alternate",
        trigger_rule='fuel_reserve', trigger_signal='fuel_kg',
        trigger_thresh=0.40,
        solution_name="Immediate Divert + Minimum Power",
        reward_score=0.76, safety_score=0.96,
    ),
]


# =============================================================================
# TRIPLE-LOCK GATE
# =============================================================================

@dataclass
class TripleLockStatus:
    cond1_threshold:  bool  = False   # predictive threshold crossed
    cond2_confidence: bool  = False   # confidence score sufficient
    cond3_human:      bool  = False   # within human temporal window
    gate_open:        bool  = False   # all three satisfied
    best_scenario:    Optional[DreamedScenario] = None
    confidence_score: float = 0.0


# =============================================================================
# DREAMING AGENT CLASS
# =============================================================================

class DreamingAgent:
    """
    π₂ Dreaming Agent — Anticipatory Mode.

    Runs simultaneously with the execution agent on every clock tick.
    Scores all dreamed scenarios, detects materialising threats,
    and deploys pre-computed solutions when the triple-lock gate fires.

    Outputs:
      - f_pi2: intensity multiplier for r_total = r1 * f(π2)
      - micro_reward: small increment per viable dream
      - macro_reward: large spike on successful deployment
      - triple_lock: current gate status for each rule
    """

    # Dynamic weight bounds
    W1_SAFE       = 0.55   # reward weight when safe
    W1_NEAR_BREACH = 0.40  # reward weight when near-breach (safety prioritised)
    W2_SAFE       = 0.45   # safety weight when safe
    W2_NEAR_BREACH = 0.60  # safety weight when near-breach

    # Reward increments
    MICRO_REWARD  = 0.02   # per viable dream per step
    MACRO_REWARD  = 0.50   # on successful deployment

    # Confidence threshold for triple-lock cond2
    CONFIDENCE_THRESH = 0.72

    # Human temporal window (step numbers)
    HUMAN_WINDOW = (8, 60)

    def __init__(self, verbose: bool = False):
        self.scenarios       = [DreamedScenario(**vars(s)) for s in SCENARIO_LIBRARY]
        self.verbose         = verbose
        self.step_count      = 0
        self.f_pi2           = 1.0    # starts at 1.0 (neutral multiplier)
        self.deployed        = False
        self.deployed_step   = None
        self.deployed_solution = None
        self.reward_history  = []
        self.f_pi2_history   = []
        self.triple_lock_history = []

    def _compute_weights(self, any_near_breach: bool) -> Tuple[float, float]:
        """Dynamic weights shift when near-breach detected."""
        if any_near_breach:
            return self.W1_NEAR_BREACH, self.W2_NEAR_BREACH
        return self.W1_SAFE, self.W2_SAFE

    def _compute_confidence(
        self,
        scenario: DreamedScenario,
        proximity_vars: Dict,
        proximity_scores: Dict
    ) -> float:
        """
        Computes confidence that this dreamed scenario is materialising.
        Confidence is based on how closely the current proximity score
        matches the scenario's trigger threshold.
        """
        current_score = proximity_scores.get(scenario.trigger_rule, 0.0)

        if current_score <= 0.0:
            return 0.0

        # Confidence rises as proximity score approaches trigger threshold
        confidence = min(1.0, current_score / max(scenario.trigger_thresh, 0.01))
        return round(confidence, 4)

    def _evaluate_triple_lock(
        self,
        scenario: DreamedScenario,
        confidence: float,
        any_near_breach: bool
    ) -> TripleLockStatus:
        """Evaluates all three triple-lock conditions for a scenario."""
        lock = TripleLockStatus()
        lock.best_scenario   = scenario
        lock.confidence_score = confidence

        lock.cond1_threshold  = any_near_breach
        lock.cond2_confidence = confidence >= self.CONFIDENCE_THRESH
        lock.cond3_human      = (self.HUMAN_WINDOW[0]
                                  <= self.step_count
                                  <= self.HUMAN_WINDOW[1])
        lock.gate_open        = (lock.cond1_threshold
                                  and lock.cond2_confidence
                                  and lock.cond3_human)
        return lock

    def step(
        self,
        proximity_vars: Dict,
        proximity_scores: Dict,
        any_near_breach: bool,
        r1: float
    ) -> Tuple[float, float, Optional[TripleLockStatus]]:
        """
        Core dreaming step — called every timestep in parallel with execution agent.

        Args:
            proximity_vars:   raw proximity variable values from digital twin
            proximity_scores: normalised scores (0=safe, 1=breach) from π₁
            any_near_breach:  flag from execution agent
            r1:               current base reward from execution agent

        Returns:
            f_pi2:            current reward intensity multiplier
            step_reward:      reward earned this step (micro or macro)
            best_lock:        best triple-lock status if gate open, else None
        """
        self.step_count += 1
        w1, w2 = self._compute_weights(any_near_breach)

        step_reward = 0.0
        best_lock   = None
        viable_count = 0

        # ── Score all scenarios ───────────────────────────────────────────────
        for scenario in self.scenarios:
            confidence = self._compute_confidence(
                scenario, proximity_vars, proximity_scores
            )
            scenario.confidence = confidence

            # Weighted objective function
            scenario.weighted_score = round(
                w1 * scenario.reward_score + w2 * scenario.safety_score, 4
            )

            # A scenario is viable if it has any relevance to current state
            scenario.viable = confidence > 0.1

            if scenario.viable:
                viable_count += 1
                # Micro-reward per viable dream
                step_reward += self.MICRO_REWARD * scenario.weighted_score

        # ── Find best scenario and evaluate triple-lock ───────────────────────
        # Filter to scenarios triggered by current near-breach rules
        relevant = [s for s in self.scenarios
                    if s.viable and proximity_scores.get(s.trigger_rule, 0) > 0.1]

        if relevant:
            best = max(relevant, key=lambda s: s.weighted_score)
            lock = self._evaluate_triple_lock(best, best.confidence, any_near_breach)

            # ── DEPLOYMENT: triple-lock gate opens ────────────────────────────
            if lock.gate_open and not self.deployed and r1 > 0:
                self.deployed          = True
                self.deployed_step     = self.step_count
                self.deployed_solution = best.solution_name
                step_reward           += self.MACRO_REWARD   # big intensity spike
                best_lock              = lock

                print(f"\n  ★  TRIPLE-LOCK GATE OPENS — step {self.step_count}")
                print(f"       Cond 1 (threshold) : {'✓' if lock.cond1_threshold  else '✗'}")
                print(f"       Cond 2 (confidence): {'✓' if lock.cond2_confidence else '✗'}"
                      f"  [{best.confidence:.3f} ≥ {self.CONFIDENCE_THRESH}]")
                print(f"       Cond 3 (human)     : {'✓' if lock.cond3_human      else '✗'}"
                      f"  [step {self.step_count} in {self.HUMAN_WINDOW}]")
                print(f"       Deploying: {best.solution_name}")
                print(f"       Score: {best.weighted_score:.4f} "
                      f"(R:{best.reward_score} × {w1} + S:{best.safety_score} × {w2})")

            elif lock.gate_open and self.deployed:
                best_lock = lock   # gate remains open, solution already deployed

        # ── Update f(π₂) ─────────────────────────────────────────────────────
        # f(π₂) accumulates micro-rewards (ripples) and macro-rewards (spikes)
        self.f_pi2 += step_reward
        self.f_pi2  = round(min(self.f_pi2, 5.0), 4)   # cap at 5x multiplier

        self.reward_history.append(step_reward)
        self.f_pi2_history.append(self.f_pi2)
        self.triple_lock_history.append(best_lock)

        if self.verbose:
            self._print_status(viable_count, step_reward, best_lock, w1, w2)

        return self.f_pi2, step_reward, best_lock

    def _print_status(self, viable_count: int, step_reward: float,
                       lock: Optional[TripleLockStatus], w1: float, w2: float):
        lock_str = "GATE OPEN" if (lock and lock.gate_open) else "gate closed"
        print(f"  [π₂ step {self.step_count:04d}] "
              f"f(π₂)={self.f_pi2:.4f} | "
              f"viable dreams:{viable_count} | "
              f"step_reward:{step_reward:.4f} | "
              f"w₁={w1} w₂={w2} | {lock_str}")

    def summary(self) -> Dict:
        return {
            'total_steps':        self.step_count,
            'final_f_pi2':        self.f_pi2,
            'total_step_rewards': round(sum(self.reward_history), 4),
            'deployed':           self.deployed,
            'deployed_step':      self.deployed_step,
            'deployed_solution':  self.deployed_solution,
            'scenarios_in_library': len(self.scenarios),
        }

    def print_summary(self):
        s = self.summary()
        print("\n  ── π₂ Dreaming Agent Summary ────────────────────────────")
        print(f"  Total steps        : {s['total_steps']}")
        print(f"  Final f(π₂)        : {s['final_f_pi2']}")
        print(f"  Total step rewards : {s['total_step_rewards']}")
        print(f"  Deployed           : {s['deployed']}")
        print(f"  Deployed at step   : {s['deployed_step']}")
        print(f"  Solution deployed  : {s['deployed_solution']}")
        print(f"  Scenario library   : {s['scenarios_in_library']} scenarios")
        print("  ──────────────────────────────────────────────────────────")


# =============================================================================
# SELF-TEST
# =============================================================================

if __name__ == "__main__":
    print("=" * 65)
    print("  I.R.I.S. — Dreaming Agent (π₂) Self-Test")
    print("=" * 65)

    agent = DreamingAgent(verbose=True)

    # Simulate normal flight — no near-breach
    print("\n  Phase 1: Normal flight (5 steps)")
    normal_pv    = {'gnss_signal': 90.0, 'mach': 0.78,
                    'altitude_m': 8500.0, 'alpha_deg': 4.0, 'fuel_kg': 12000.0}
    normal_scores = {'communication': 0.0, 'speed_envelope': 0.0,
                     'stall_margin': 0.0, 'fuel_reserve': 0.0}

    for _ in range(5):
        f, r, lock = agent.step(normal_pv, normal_scores,
                                any_near_breach=False, r1=1.0)

    # Simulate GNSS degradation — near-breach building
    print("\n  Phase 2: GNSS degradation (10 steps)")
    for i in range(10):
        degraded_scores = {'communication': 0.3 + i * 0.05,
                           'speed_envelope': 0.0, 'stall_margin': 0.0,
                           'fuel_reserve': 0.0}
        f, r, lock = agent.step(normal_pv, degraded_scores,
                                any_near_breach=(i > 4), r1=1.0)

    agent.print_summary()
    print("\n  π₂ Dreaming Agent self-test complete.")
    print("=" * 65)
